-- 코드를 입력하세요
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME < AI.DATETIME
ORDER BY AI.DATETIME ASC
;

# SELECT ANIMAL_ID, I.NAME
# FROM ANIMAL_INS I JOIN ANIMAL_OUTS O USING(ANIMAL_ID)
# WHERE I.DATETIME > O.DATETIME
# ORDER BY I.DATETIME ASC