-- 코드를 입력하세요
SELECT B.BOOK_ID, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK B
WHERE B.PUBLISHED_DATE BETWEEN '2021-01-01' AND '2021-12-31'
AND B.CATEGORY = '인문'
ORDER BY B.PUBLISHED_DATE ASC;